CREATE TABLE "rulesets" (
	"id" INTEGER PRIMARY KEY,
	"name" TEXT NOT NULL,
   	"enabled" BOOLEAN DEFAULT true
);
CREATE TABLE "hosts" (
	"id" INTEGER PRIMARY KEY,
	"host" TEXT NOT NULL,
 	"ruleset_id" INTEGER NOT NULL REFERENCES rulesets (id) ON DELETE CASCADE
);
CREATE TABLE "rules" (
	"id" INTEGER PRIMARY KEY,
	"from" TEXT NOT NULL,
	"to" TEXT NOT NULL,
 	"ruleset_id" INTEGER NOT NULL REFERENCES rulesets (id) ON DELETE CASCADE
);
CREATE TABLE "cookies" (
	"id" INTEGER PRIMARY KEY,
	"host" TEXT NOT NULL,
 	"name" TEXT NOT NULL,
	"ruleset_id" INTEGER NOT NULL REFERENCES rulesets (id) ON DELETE CASCADE
);
CREATE TABLE "exclusions" (
	"id" INTEGER PRIMARY KEY,
	"pattern" TEXT NOT NULL,
	"ruleset_id" INTEGER NOT NULL REFERENCES rulesets (id) ON DELETE CASCADE
)